export type Difficulty = "easy" | "medium" | "hard";

export type PracticeSample = {
  difficulty: Difficulty;
  text: string;
};

const easy = [
  "The sun came up over the hill and filled the small room with warm light. A blue cup sat by the open book while birds sang in the garden.",
  "We took the long road home because the air was cool and the sky was clear. Every turn gave us a new view of the green fields.",
  "A good day can start with a glass of water, a deep breath, and one simple plan. Small steps often lead to the best kind of progress.",
  "Mia put fresh bread on the table and called her friends inside. They shared a warm meal, told old stories, and laughed until the room felt bright.",
  "The little dog ran across the yard to catch a red ball. It came back with a proud look and waited for the next throw.",
  "Ben likes to read near the window when rain taps on the glass. He keeps a soft chair there and a lamp for dark days.",
  "Our train left the town just after nine and moved past farms, rivers, and quiet roads. We watched the world slide by from our seats.",
  "A walk in the park can clear the mind after a busy day. The trees move in the wind, and each slow step helps the body rest.",
  "She made a short list before going to the shop. Apples, rice, milk, and tea were all she needed for a calm week at home.",
  "The class met under a large tree to draw maps of the school garden. Each group found a new path and marked it with a bright line.",
  "At noon, the beach was warm and the sea was still. We left our shoes near the rocks and walked where the waves met the sand.",
  "I keep a small note by my desk that says to begin before I feel ready. It helps me turn a hard task into an easy first step.",
  "The old clock in the hall made a soft sound every hour. No one paid much mind, but the house felt quiet when it stopped.",
  "They planted seeds in neat rows and gave them water each morning. Soon, small green leaves pushed through the dark and soft ground.",
  "A new song played on the radio as we cleaned the room. The work felt light because we moved in time and sang every word.",
  "Sam found a smooth stone beside the lake and put it in his pocket. Its round shape would help him remember the peaceful place.",
  "The first bus was full, so we waited for the next one. That small delay gave us time to buy hot tea and watch the town wake.",
  "Her bag held a pen, a map, a warm coat, and a book. She was ready for a simple trip with no strict plan and plenty of time.",
  "The moon rose above the roofs while the last shops closed. People walked home in pairs, and soft light fell across the empty street.",
  "A kind word can change the tone of a long day. It takes only a moment to listen, smile, and let someone know they matter.",
  "We made soup with fresh beans, sweet corn, and a bit of salt. The pot stayed warm while everyone found a place at the table.",
  "The young cat slept on a pile of clean clothes. When we tried to move it, one green eye opened and then closed again.",
  "A small bridge crossed the stream at the edge of town. From the middle, we could see bright fish move under the clear water.",
  "I opened the door to let in the cool night air. Far away, a train gave one long call before the sound faded into silence.",
  "Our team met early to share ideas and choose one clear goal. By lunch, each person knew what to do and why it was useful.",
  "The red kite rose high when the wind grew strong. Its long tail danced over the field while the children ran below it.",
  "Every shelf in the room held a different kind of treasure. There were books, shells, old coins, and photos from trips near and far.",
  "He turned off the phone and sat with a blank page. After a quiet minute, the right words began to come one by one.",
  "The cafe on the corner opens before dawn. Warm light, fresh bread, and the smell of coffee welcome the first guests of the day.",
  "We found a shady place beside the path and stopped to rest. A cool breeze moved through the leaves as clouds crossed the sun.",
  "The baby bird stood at the edge of the nest and spread its wings. It waited, tried once, and then flew to the next branch.",
  "A clean desk leaves space for a clear thought. Put away what you do not need, keep one task close, and begin with care.",
  "The boat moved slowly across the lake as evening came. Golden light touched the water, and the town grew small behind us.",
  "I wrote the date at the top of the page and listed three good things. This simple habit helps me notice joy in an ordinary day.",
] as const;

const medium = [
  "Before the meeting began, Nora reviewed her notes, silenced her phone, and opened a fresh document. Preparation gave her the confidence to speak clearly when the room became busy.",
  "The museum courtyard was surprisingly peaceful: pale stone, rustling leaves, and a narrow fountain softened the noise of the city beyond its walls.",
  "Although the forecast promised rain, the afternoon remained bright and breezy. We carried our umbrellas anyway, then used them as shade during the long walk home.",
  "A reliable routine does not need to be complicated. Choose a useful task, protect a little time, and repeat the process until effort becomes familiar.",
  "Our neighborhood library hosts a monthly exchange where readers bring books they have finished and leave with unexpected discoveries from someone else's shelf.",
  "The recipe looked simple, but timing mattered: toast the spices first, add the vegetables slowly, and wait until the sauce becomes smooth before serving.",
  "When the power returned, every lamp blinked at once. The refrigerator hummed, the clock flashed, and a cheer rose from the apartment upstairs.",
  "Curiosity makes an ordinary journey richer. Notice the street names, ask why the buildings look different, and follow the quiet path that is not on the map.",
  "The designer moved the yellow chair closer to the window; suddenly, the entire room felt balanced. One thoughtful change can solve a problem that seemed much larger.",
  "After several careful attempts, the paper glider crossed the classroom and landed beside the door. The students measured its path and adjusted the next design.",
  "Leah keeps separate lists for urgent work, future ideas, and tiny tasks. This system protects her attention without asking her memory to hold everything at once.",
  "The evening market offered roasted nuts, bright flowers, handmade bowls, and music from a three-piece band. We wandered slowly, letting each stall surprise us.",
  "Good communication begins before anyone speaks. Pay attention to the room, notice what people need, and choose words that make the next step easier.",
  "The trail became steeper after the wooden bridge, yet the view widened with every turn. At the top, the valley looked calm, distant, and completely worth the climb.",
  "During the train delay, strangers began trading travel stories. What started as an inconvenience became a lively hour of recommendations, jokes, and shared snacks.",
  "A photographer returned to the same corner each season. Over time, her images revealed small changes in the trees, storefronts, shadows, and people passing through.",
  "Marcus repaired the loose shelf with a borrowed drill and patient measurements. The final result was not perfect, but it was strong, level, and built by hand.",
  "The workshop ended with a useful question: what is one improvement small enough to begin today? Everyone wrote an answer and placed it beside their keyboard.",
  "Clouds gathered above the stadium, but the players continued warming up. A brief shower cooled the field, cleared the stands, and left the evening sky brilliantly pink.",
  "Instead of rushing through breakfast, we opened the balcony doors and made another pot of tea. Ten unplanned minutes changed the pace of the entire morning.",
  "The community garden thrives because everyone contributes differently. Some people plant, others repair tools, and several neighbors deliver the harvest to local kitchens.",
  "An effective workspace should support the task at hand. Comfortable light, a clear surface, and fewer distractions can make deep concentration feel almost natural.",
  "Priya checked the address twice before sending the parcel. Inside, she included a short letter, two photographs, and the scarf she had finished last winter.",
  "Learning a new skill often feels slow because progress hides inside repetition. Keep practicing carefully; speed usually arrives after the movement becomes comfortable.",
  "The guide pointed toward a narrow passage between the rocks. Beyond it, we discovered a quiet cove where clear water reflected the cliffs like glass.",
  "At the annual fair, teams raced homemade carts down a gentle hill. Colorful wheels, clever names, and enthusiastic cheering mattered more than the final times.",
  "The editor removed several impressive sentences because they distracted from the main idea. Clear writing often depends on knowing what the reader does not need.",
  "A sudden breeze lifted the papers from the outdoor table. Four people chased the pages across the square, laughing as each runaway sheet was safely recovered.",
  "We compared three possible routes and chose the slower coastal road. The extra hour brought sea views, quiet villages, and the best lunch of the trip.",
  "The orchestra tuned in waves of scattered sound; then the conductor raised one hand, and the crowded hall became perfectly still.",
  "Rather than replace the scratched table, Elena sanded the surface and added a clear finish. The marks remained visible, but now they felt like part of its story.",
  "The science club built a weather station behind the gym. Each morning, students record temperature, rainfall, wind direction, and any unusual changes in the sky.",
  "A thoughtful pause can prevent a careless reply. Read the message again, decide what matters most, and answer with enough detail to move the conversation forward.",
] as const;

const hard = [
  "At 7:45 a.m., the research team re-checked its equipment: two pressure gauges, a temperature sensor, and a weather-resistant camera. Nothing could be left to chance.",
  "The proposal's central question - how might a crowded city reduce noise without limiting movement? - led to three sharply different, data-driven experiments.",
  "Version 2.4.1 fixed the login issue, improved load time by 18%, and removed a rarely used setting; however, several users still reported inconsistent results.",
  "\"Measure twice, cut once,\" Imani said, marking a 36.5-centimeter line across the oak panel. The workshop fell quiet as the electric saw started.",
  "The cafe's Wi-Fi password was written beneath the menu: Bloom!2026. After connecting, Theo uploaded 14 files, replied to six messages, and ordered another espresso.",
  "A well-structured argument connects evidence to conclusion; it does not merely place impressive statistics - 42%, 3.7 million, or $9.5 billion - beside a confident claim.",
  "On Tuesday, flight AX-108 changed gates from B12 to C7. Passengers had 23 minutes to cross the terminal, re-scan their passes, and board.",
  "The archive contains letters dated 1894-1902, hand-drawn maps, and a 12-page index. Handle each item carefully; ink and paper both weaken with age.",
  "When the server reached 92% capacity, an automated alert asked: \"Scale now or review usage?\" The on-call engineer chose review, then found a looping backup job.",
  "To make the citrus glaze, combine 1/2 cup sugar, 2 tbsp lemon juice, and a pinch of salt; simmer for 6-8 minutes, stirring continuously.",
  "The contract seemed straightforward - until section 8(b) referred to appendix C-2, which defined \"reasonable notice\" as no fewer than 15 business days.",
  "An unusually cold front moved southeast at 35 km/h, dropping the temperature from 21 degrees C to 9 degrees C before midnight. Gardeners covered young plants with cloth.",
  "The speaker asked everyone to compare three ideas: efficiency, resilience, and trust. \"A fast system isn't useful,\" she argued, \"if no one believes it will work.\"",
  "Room 3-A holds the prototype: a solar-powered pump, four lithium-ion cells, and a palm-sized controller. Do not disconnect cable #4 while the indicator is orange.",
  "Our final itinerary included Kyoto, Kanazawa, and Tokyo - a 1,120-kilometer loop completed in 11 days. Rail passes cost $350 per traveler.",
  "The test results were mixed: response time improved by 31 ms, memory use fell 7%, but battery demand increased. The team scheduled a follow-up for 09/14.",
  "Please rename the folder \"Q3_launch-final\" before 5:00 p.m.; then share read-only access with design@northstar.example and archive the older copy.",
  "A 5-kilometer trail may sound manageable, yet the 640-meter climb changes the calculation. Carry 1.5 liters of water, a map, and a light jacket.",
  "The reviewer's note was concise: \"Strong opening; unclear transition on page 17; excellent evidence in sections 4-6.\" We revised the middle first.",
  "At precisely 00:01, the observatory rotated its 2.1-meter telescope toward coordinates 18h 36m, +38 degrees 47 minutes. Thin clouds delayed the first image.",
  "The budget assigns $24,800 to materials, $6,200 to transport, and a 12% contingency fund. Any change above $1,000 requires two signatures.",
  "For security, create a 16-character passphrase with upper- and lowercase letters, numbers, and symbols - but never reuse an old password or personal date.",
  "The lab's pH readings shifted from 6.8 to 7.3 after 90 seconds. Because the change exceeded +/-0.2, the technician calibrated the meter again.",
  "A margin of error of +/-3% sounds small, but context matters: who was surveyed, how were questions phrased, and what happened during data collection?",
  "The 19th-century station has been reimagined as a co-working space; ticket windows became desks, while the old platform now hosts a Saturday market.",
  "In the command line, type npm run build - not npm run dev - then confirm that the output includes \"compiled successfully\" and zero unresolved warnings.",
  "The recipe serves 6-8 people and scales unevenly: doubling the flour works, but spices should increase by roughly 1.5 times before you taste and adjust.",
  "A bright object crossed the northwest sky at 22:17:06, remained visible for 4.2 seconds, and split into three fragments near the horizon.",
  "The invoice lists PO #7741, an issue date of 28/07/2026, and payment terms of net 30. Questions should reference the eight-digit client ID.",
  "Although the machine-learning model reached 94.6% accuracy, it failed disproportionately on low-light images - a limitation the summary must state clearly.",
  "The trail marker read \"Summit 2.75 mi ->,\" but a storm was moving in from the west. We checked the radar, discussed the risk, and turned around.",
  "Three outcomes remain possible: (1) approve the pilot, (2) request a smaller trial, or (3) postpone the decision until Q1. Each option has a measurable cost.",
  "During the 48-hour design sprint, the team interviewed 12 customers, tested 5 prototypes, and rejected its favorite concept - because the evidence pointed elsewhere.",
] as const;

export const sampleBank: PracticeSample[] = [
  ...easy.map((text) => ({ difficulty: "easy" as const, text })),
  ...medium.map((text) => ({ difficulty: "medium" as const, text })),
  ...hard.map((text) => ({ difficulty: "hard" as const, text })),
];
